package org.comon.streamlauncher.domain.model.preset

data class Preset(
    val id: Int = 0, // Auto-generated by Room
    val name: String,
    // 1. Home Image Settings (4 regions)
    val hasTopLeftImage: Boolean,
    val hasTopRightImage: Boolean,
    val hasBottomLeftImage: Boolean,
    val hasBottomRightImage: Boolean,
    val topLeftIdleUri: String?,
    val topLeftExpandedUri: String?,
    val topRightIdleUri: String?,
    val topRightExpandedUri: String?,
    val bottomLeftIdleUri: String?,
    val bottomLeftExpandedUri: String?,
    val bottomRightIdleUri: String?,
    val bottomRightExpandedUri: String?,
    
    // 2. Feed Settings
    val hasFeedSettings: Boolean, // Whether feed settings are included in this preset
    val useFeed: Boolean,
    val youtubeChannelId: String,
    val chzzkChannelId: String,
    
    // 3. App Drawer Settings
    val hasAppDrawerSettings: Boolean,
    val appDrawerColumns: Int,
    val appDrawerRows: Int,
    val appDrawerIconSizeRatio: Float,
    
    // 4. Wallpaper Settings
    val hasWallpaperSettings: Boolean,
    val wallpaperUri: String?,
    val enableParallax: Boolean,
    
    // 5. Theme Color Settings
    val hasThemeSettings: Boolean,
    val themeColorHex: String?, // Null means system default or dynamic color
    
    val createdAt: Long = System.currentTimeMillis()
)
